### ISSUE TITLE
Descriptive error messages (hopefully an object!) to get which package gives conflicts

### ISSUE THREAD

**Issue by miyagawa** [Perl-Toolchain-Gang/CPAN-Meta-Requirements#24]
Right now when merging two requirements, all I get is a string error saying "illegal requirements: minimum exceeds maximum at ..." with a giant stacktrace.

This isn't really helpful to present to users (using cpanm or Carmel), I'd like to display which requirement for which module gets a conflict. That should actually be doable if I walk down each module individually (because I have access to old and new requirement to add), but when calling `->add_requirements`, the error message doesn't give any clue which module has the conflict.

For now like said above, I'll write my own merge wrapper to try to get them, but would be nice if the error message is more descriptive from CMR!

**Comment by rjbs** [comment]
I've just pushed up a "detailed-errors" branch.  Could you let me know what you think?  Give it a spin.

**Comment by miyagawa** [comment]
Looks good :+1:

**Comment by rjbs** [comment]
This is now in a trial release on the CPAN.

https://metacpan.org/release/RJBS/CPAN-Meta-Requirements-2.137-TRIAL

**Comment by Leont** [comment]
Closing this as it has been fixed in 2015
