### ISSUE TITLE
Does 0.8.0 really not fulfil ">=0.6" ?

### ISSUE THREAD

**Issue by mschilli** [Perl-Toolchain-Gang/CPAN-Meta-Requirements#29]
I know that comparing versions can be tricky, but is it really reasonable to reject version 0.8.0 when someone requires 0.6 and above?

use CPAN::Meta::Requirements;
my $build_requires = CPAN::Meta::Requirements->new;
$build_requires->add_minimum('Thrift' => '0.6');
if( $build_requires->accepts_module( 'Thrift' => '0.8.0' ) ) {
    print "yes!\n";
} else {
    print "nooo ...\n";
}

**Comment by miyagawa** [comment]
Yes, because 0.8.0 is equal to 0.008000 in numeric.

**Comment by mschilli** [comment]
If 0.8.0 is 0.008000, why isn't 0.6 equal to 0.006 in "numeric"?

**Comment by miyagawa** [comment]
0.6.0 is. But 0.6 isn't.

**Comment by mschilli** [comment]
So if a module author releases 0.6.1 after 0.6, this will break every module on CPAN requiring 0.5 and above?

**Comment by miyagawa** [comment]
Correct. A CPAN dist shouldn't switch version number scheme, at least not
in the middle of minor releases.

Read more at
http://www.dagolden.com/index.php/369/version-numbers-should-be-boring/

**Comment by mschilli** [comment]
Okay, I'll fix my dependency on Thrift 0.6 to 0.6.1 and hope that the author won't revert to a two-number scheme. Thanks!

**Comment by karenetheridge** [comment]
Well, Thrift is still indexed to 0.8.0 rather than the new 0.9.0 release,
because its package statement was altered:

https://metacpan.org/source/GSLIN/Thrift-0.9.0//lib/Thrift.pm

```
Thrift                         0.008000  G/GS/GSLIN/Thrift-0.8.0.tar.gz
Thrift::BinaryProtocol         0.009000  G/GS/GSLIN/Thrift-0.9.0.tar.gz
Thrift::BinaryProtocolFactory  0.009000  G/GS/GSLIN/Thrift-0.9.0.tar.gz
Thrift::BufferedTransport      0.009000  G/GS/GSLIN/Thrift-0.9.0.tar.gz
Thrift::BufferedTransportFactory 0.009000  G/GS/GSLIN/Thrift-0.9.0.tar.gz
Thrift::ForkingServer          0.009000  G/GS/GSLIN/Thrift-0.9.0.tar.gz
Thrift::FramedTransport        0.009000  G/GS/GSLIN/Thrift-0.9.0.tar.gz
Thrift::HttpClient             0.009000  G/GS/GSLIN/Thrift-0.9.0.tar.gz
```

**Comment by dagolden** [comment]
Side note: this is why I recommend that people *always* use a leading `v` when doing anything involving version tuples.  It's much less confusing when someone drops the last part (as long as they keep the leading `v`):  `v0.6.0` == `v0.6` == `0.006`.
