### ISSUE TITLE
Wrong installation into site on 5.8.9 [rt.cpan.org #88141]

### ISSUE THREAD

**Issue by dagolden** [Perl-Toolchain-Gang/CPAN-Meta-Requirements#5]
https://rt.cpan.org/Ticket/Display.html?id=88141

    On perl-5.8.9 version 2.120351 is installed in core.
    Version 2.122 installs into site, not into core.
    Please set a proper INSTALLDIRS.
    
    5.8.9 favors core over site.
      @INC:
        /usr/local/lib/perl5/5.8.9/x86_64-linux
        /usr/local/lib/perl5/5.8.9
        /usr/local/lib/perl5/site_perl/5.8.9/x86_64-linux
        /usr/local/lib/perl5/site_perl/5.8.9
    
    Hence:
    
      CPAN.pm: Building L/LE/LEONT/CPAN-Meta-Check-0.007.tar.gz
    
    Warning: Prerequisite 'CPAN::Meta => 2.120920' for 'LEONT/CPAN-Meta-Check-0.007.tar.gz' failed when processing 'DAGOLDEN/CPAN-Meta-2.132140.tar.gz' with 'make_test => NO'. Continuing, but chances to succeed are limited.
    cp lib/CPAN/Meta/Check.pm blib/lib/CPAN/Meta/Check.pm
    Manifying blib/man3/CPAN::Meta::Check.3
      LEONT/CPAN-Meta-Check-0.007.tar.gz
      /usr/bin/make -- OK
    Running make test
    PERL_DL_NONLAZY=1 /usr/local/bin/perl5.8.9-nt "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
    t/00-compile.t ............ CPAN::Meta::Requirements version 2.12092 required--this is only version 2.120351 at lib/CPAN/Meta/Check.pm line 13.
    BEGIN failed--compilation aborted at lib/CPAN/Meta/Check.pm line 13.
    Compilation failed in require at -e line 1.
    t/00-compile.t ............ 1/1 
    #   Failed test 'CPAN::Meta::Check loaded ok'
    #   at t/00-compile.t line 62.
    #                   ''
    #     doesn't match '(?s-xim:^\s*CPAN::Meta::Check ok)'
    # Looks like you failed 1 test of 1.
    t/00-compile.t ............ Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/1 subtests 
    t/10-basics.t ............. CPAN::Meta version 2.12092 required--this is only version 2.120351 at t/10-basics.t line 8.
    BEGIN failed--compilation aborted at t/10-basics.t line 8.
    t/10-basics.t ............. Dubious, test returned 255 (wstat 65280, 0xff00)
    No subtests run 
    t/release-pod-coverage.t .. skipped: these tests are for release candidate testing
    t/release-pod-syntax.t .... skipped: these tests are for release candidate testing

**Comment by xdg** [comment]
Should be fixed for a while with the UNINST rule in Makefile.PL.  Closing.
